In [ ]:
11. Customer Purchasing Behavior

In [ ]:
Data Cleaning


Q1. Check whether the dataset contains any null or missing values. If found, handle
them appropriately.
Q2. Identify and remove any duplicate rows from the dataset.
Q3. Check the 'age' column for unrealistic values (e.g., 0 or 200). Filter and display such
rows if any exist.
Q4. The 'loyalty_score' should be between 0 and 10. Check if any values fall outside this
range.
Q5. Verify that all numerical columns have the correct data type. Convert any column
that has an incorrect type.
Q6. Detect outliers in the 'purchase_amount' and 'annual_income' columns using the
IQR method.

In [3]:
import pandas as pd
import numpy as np

In [4]:
df= pd.read_csv(r"C:\Users\Parth\OneDrive\Desktop\student_prrform_analyzer\Customer Purchasing Behaviors.csv")
print(df.head())
print(df.shape)
df

   user_id  age  annual_income  purchase_amount  loyalty_score region  \
0        1   25          45000              200            4.5  North
1        2   34          55000              350            7.0  South
2        3   45          65000              500            8.0   West
3        4   22          30000              150            3.0   East
4        5   29          47000              220            4.8  North

   purchase_frequency
0                  12
1                  18
2                  22
3                  10
4                  13
(238, 7)

,user_id,age,annual_income,purchase_amount,loyalty_score,region,purchase_frequency
0,1,25,45000,200,4.5,North,12
1,2,34,55000,350,7.0,South,18
2,3,45,65000,500,8.0,West,22
3,4,22,30000,150,3.0,East,10
4,5,29,47000,220,4.8,North,13
...,...,...,...,...,...,...,...
233,234,40,60000,450,7.2,West,20
234,235,38,59000,430,6.9,North,20
235,236,54,74000,630,9.4,South,27
236,237,32,52000,360,5.8,West,18
237,238,31,51000,340,5.6,North,17

In [94]:
# Q1. Check whether the dataset contains any null or missing values. If found, handle them appropriately.

print(df.isnull().sum())
print("Total missing Values:", df.isnull().sum().sum())

#handle if any
df['age'].fillna(df['age'].median(),inplace=True)
df['annual_income'].fillna(df['annual_income'].median(),inplace=True)
df['purchase_amount'].fillna(df['purchase_amount'].median(),inplace=True)
df['loyalty_score'].fillna(df['loyalty_score'].median(),inplace=True)
df['region'].fillna(df['region'].mode()[0],inplace=True)
df['purchase_frequency'].fillna(df['purchase_frequency'].median(),inplace=True)

print("After handling: ", df.isnull().sum().sum())

user_id                0
age                    0
annual_income          0
purchase_amount        0
loyalty_score          0
region                 0
purchase_frequency     0
age_group              0
loyality_categories    0
loyalty_categories     0
Income_Groups          0
income_group           0
dtype: int64
Total missing Values: 0
After handling:  0

C:\Users\Parth\AppData\Local\Temp\ipykernel_17228\903506053.py:7: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['age'].fillna(df['age'].median(),inplace=True)
C:\Users\Parth\AppData\Local\Temp\ipykernel_17228\903506053.py:8: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['annual_income'].fillna(df['annual_income'].median(),inplace=True)
C:\Users\Parth\AppData\Local\Temp\ipykernel_17228\903506053.py:9: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['purchase_amount'].fillna(df['purchase_amount'].median(),inplace=True)
C:\Users\Parth\AppData\Local\Temp\ipykernel_17228\903506053.py:10: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['loyalty_score'].fillna(df['loyalty_score'].median(),inplace=True)
C:\Users\Parth\AppData\Local\Temp\ipykernel_17228\903506053.py:11: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['region'].fillna(df['region'].mode()[0],inplace=True)
C:\Users\Parth\AppData\Local\Temp\ipykernel_17228\903506053.py:12: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['purchase_frequency'].fillna(df['purchase_frequency'].median(),inplace=True)

In [96]:
#Q2. Identify and remove any duplicate rows from the dataset.

# check

Duplicate_rows= df.duplicated().sum()
print("Duplicate rows:",Duplicate_rows)

# remove

df.drop_duplicates(inplace=True)
print(df.shape)

Duplicate rows: 0
(238, 12)

In [ ]:
#Q3. Check the 'age' column for unrealistic values (e.g., 0 or 200). Filter and display such rows if any exist.

# filter rows with unrealstic age
age = df[(df['age'] <=0) | (df['age'] >= 120)]
print("Unrealistic age: ",len(age))

# Remove
df= df[(df['age'] > 0) & (df['age'] <= 120)]
print("Shape after cleaning age: ",df.shape)

In [100]:
#Q4. The 'loyalty_score' should be between 0 and 10. Check if any values fall outside this range.

#check

terrible_score= df[(df['loyalty_score'] < 0) | (df['loyalty_score'] > 10)]
print("Invalid loyalty_score: ",len(terrible_score))

#Remove
df= df[(df['loyalty_score'] >= 0) & (df['loyalty_score'] <= 10)]
print("shape after cleaning loyalty_score: ",df.shape)

Invalid loyalty_score:  0
shape after cleaning loyalty_score:  (238, 12)

In [14]:
#Q5. Verify that all numerical columns have the correct data type. Convert any column that has an incorrect type.

print(df.dtypes)

# convert
df['age']= pd.to_numeric(df['age'])
df['annual_income']= pd.to_numeric(df['annual_income'])
df['purchase_amount']= pd.to_numeric(df['purchase_amount'])
df['loyalty_score']= df['loyalty_score'].astype(float)
df['purchase_frequency']= pd.to_numeric(df['purchase_frequency'])

# verify
print("shape after conversion: ",df.dtypes)

user_id                 int64
age                     int64
annual_income           int64
purchase_amount         int64
loyalty_score         float64
region                    str
purchase_frequency      int64
dtype: object
shape after conversion:  user_id                 int64
age                     int64
annual_income           int64
purchase_amount         int64
loyalty_score         float64
region                    str
purchase_frequency      int64
dtype: object

In [25]:
#Q6. Detect outliers in the 'purchase_amount' and 'annual_income' columns using the IQR method.

for col in ['annual_income','purchase_amount']:
    Q1= df[col].quantile(0.25)
    Q3= df[col].quantile(0.75)

    IQR= Q3 - Q1
    lower= Q1 - 1.5*IQR
    upper= Q3 + 1.5*IQR

    outliers= df[(df[col] < lower) | (df[col] > upper)]

    print(f"\n---------- {col} ----------")
    print(f"Q1= {Q1}, Q3= {Q3}, IQR= {IQR}")
    print(f"Lower Bound= {lower}, Upper Bound= {upper}")
    print(f"Outliers Found: {len(outliers)}")
    print(outliers[[col]])

---------- annual_income ----------
Q1= 50000.0, Q3= 66750.0, IQR= 16750.0
Lower Bound= 24875.0, Upper Bound= 91875.0
Outliers Found: 0
Empty DataFrame
Columns: [annual_income]
Index: []

---------- purchase_amount ----------
Q1= 320.0, Q3= 527.5, IQR= 207.5
Lower Bound= 8.75, Upper Bound= 838.75
Outliers Found: 0
Empty DataFrame
Columns: [purchase_amount]
Index: []

In [ ]:
GroupBy & Aggregation
Q7. Find the average purchase amount for each region.
Q8. Count the number of customers in each region.
Q9. Divide customers into age groups (20-29, 30-39, 40-49, 50+) and find the average
loyalty score for each group.
Q10. Which region has the highest average purchase frequency?
Q11. Find the maximum and minimum annual income for each region.
Q12. Divide customers into three loyalty categories — Low (0–4), Medium (4–7), High
(7–10) — and count customers in each category.
Q13. Find the total purchase amount for each age group.
Q14. Which region has the highest average loyalty score?
Q15. Divide customers into two income groups — Low Income (< 50,000) and High
Income (>= 50,000) — and compare their average purchase amount.

In [28]:
#Q7. Find the average purchase amount for each region.

q7= df.groupby('region')['purchase_amount'].mean()
q7

region
East     320.000000
North    358.589744
South    416.883117
West     510.519481
Name: purchase_amount, dtype: float64

In [33]:
#Q8. Count the number of customers in each region.

q8=df.groupby('region')['user_id'].count()
q8

region
East      6
North    78
South    77
West     77
Name: user_id, dtype: int64

In [37]:
#Q9. Divide customers into age groups (20-29, 30-39, 40-49, 50+) and find the average loyalty score for each group.

# create age group
bins= [20,30,40,50,100]
labels= ['20-29','30-39','40-49','50+']

df['age_group']= pd.cut(df['age'], bins=bins, labels=labels, right=True)

#groupby
q9= df.groupby('age_group')['loyalty_score'].mean()
q9

age_group
20-29    4.091525
30-39    6.425676
40-49    8.292000
50+      9.273333
Name: loyalty_score, dtype: float64

In [41]:
#Q10. Which region has the highest average purchase frequency? 

q10= df.groupby('region')['purchase_frequency'].mean()
q10

region
East     16.666667
North    17.653846
South    19.467532
West     22.545455
Name: purchase_frequency, dtype: float64

In [45]:
#Q11. Find the maximum and minimum annual income for each region.

q11= df.groupby('region')['annual_income'].agg(['max','min'])
q11

          max    min
region
East    60000  30000
North   70000  31000
South   75000  32000
West    75000  32000

In [60]:
#Q12. Divide customers into three loyalty categories — Low (0–4), Medium (4–7), High (7–10) — and count customers in each category.

#create bins
bins= [0,4,7,10]
labels= ["Low", "Medium", "High"]

df['loyalty_categories']= pd.cut(df['loyalty_score'], bins=bins, labels=labels, right=True)

#Groupby
q12= df.groupby('loyalty_categories')['user_id'].count()
q12

loyalty_categories
Low        23
Medium    102
High      113
Name: user_id, dtype: int64

In [49]:
#Q13. Find the total purchase amount for each age group.

q13= df.groupby('age_group')['purchase_amount'].sum()
q13

age_group
20-29    13590
30-39    29430
40-49    39690
50+      18590
Name: purchase_amount, dtype: int64

In [54]:
#Q14. Which region has the highest average loyalty score?

q14= df.groupby('region')['loyalty_score'].mean()
print(q14)
print("\nHighest:", q14.idxmax(), "→", q14.max())

region
East     5.400000
North    5.865385
South    6.725974
West     7.911688
Name: loyalty_score, dtype: float64

Highest: West → 7.911688311688312

In [70]:
#Q15. Divide customers into two income groups — Low Income (< 50,000) and High Income (>= 50,000) — and compare their average purchase amount.

#create bins
bins= [0,50000,float('inf')]
labels= ["Low Income","High Income"]

df['income_group']= pd.cut(df['annual_income'], bins=bins, labels=labels, right=False)
df['income_group']

#groupby
q15= df.groupby('income_group')['purchase_amount'].mean()
q15

income_group
Low Income     230.338983
High Income    490.000000
Name: purchase_amount, dtype: float64

In [ ]:
Pivot Table
Q1.Region-wise average purchase amount pivot banao
Q2.Age group vs Region — average loyalty score
Q3.Income group vs Region — total purchase amount
Q4.Loyalty category vs Region — customer count
Q5.Grand total ke saath region-wise summary

In [80]:
#Q1.Region-wise average purchase amount pivot banao

p1 = pd.pivot_table(df,
                    index=["region"],
                    values=['purchase_amount'],
                    aggfunc="mean").round(2)
p1

        purchase_amount
region
East             320.00
North            358.59
South            416.88
West             510.52

In [82]:
#Q2.Age group vs Region — average loyalty score

p2= pd.pivot_table(df,
                  index=["age_group"],
                  columns=['region'],
                  values=['loyalty_score'],
                  aggfunc="mean").round(2)
p2

          loyalty_score
region             East North South  West
age_group
20-29              3.83  4.33  3.50  4.30
30-39              6.97  6.32  6.35  6.55
40-49               NaN  8.44  7.94  8.54
50+                 NaN   NaN  9.39  9.22

In [99]:
#Q3.Income group vs Region — total purchase amount

p3= pd.pivot_table(df,
                  index=["income_group"],
                   columns=['region'],
                   values=['purchase_amount'],
                   aggfunc="sum")
p3

             purchase_amount
region                  East  North  South   West
income_group
Low Income               620   9260   2790    920
High Income             1300  18710  29310  38390

In [86]:
#Q4.Loyalty category vs Region — customer count

p4= pd.pivot_table(df,
                  index=["loyalty_categories"],
                  columns=["region"],
                  values=["user_id"],
                  aggfunc="count")
p4

                   user_id
region                East North South West
loyalty_categories
Low                      1     8    13    1
Medium                   4    52    27   19
High                     1    18    37   57

In [90]:
#Q5.Grand total ke saath region-wise summary

p5= pd.pivot_table(df,
                  index=["region"],
                  values=["purchase_amount","loyalty_score"],
                  aggfunc="mean").round(2)
p5

        loyalty_score  purchase_amount
region
East             5.40           320.00
North            5.87           358.59
South            6.73           416.88
West             7.91           510.52

In [91]:
df.to_csv('Cleaned_Customer_Data.csv', index=False)
print("File saved!")

File saved!

In [92]:
import os
print(os.getcwd())

C:\Users\Parth\OneDrive\Desktop\PROJECTS